# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger: none

pool:
  name: "new-agent"

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build

    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          slaztest01acr.azurecr.io/docker-helloworld:latest
          
        
    - task: Bash@3
      displayName: "Build and Push Docker Image"
      inputs:
        targetType: "inline"
        script: |
           docker login slaztest01acr.azurecr.io -u $(uid) -p $(pwd)
           docker push slaztest01acr.azurecr.io/docker-helloworld:latest
           if [ $? -ne 0 ]
             then
                echo "Docker PUSH is not successful"
                exit 1
           fi          