# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger: none

pool:
  name: "new-agent"

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
  - stage: build
    displayName: Build
    jobs:
      - job: build
        displayName: Build
        steps:
          - task: Bash@3
            displayName: "Build and Push Docker Image"
            inputs:
              targetType: "inline"
              script: |
                docker login slaztest01acr.azurecr.io -u $(uid) -p $(pwd)
                docker build -t slaztest01acr.azurecr.io/slaztest01acr:latest $(Build.SourcesDirectory)/Dockerfile
                docker push slaztest01acr.azurecr.io/slaztest01acr:latest
                if [ $? -ne 0 ]
                then
                  echo "Docker PUSH is not successful"
                  exit 1
                fi

