# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger: none

pool:
  name: "new-agent"

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build

    steps:
        
    - task: Bash@3
      displayName: "Build and Push Docker Image"
      inputs:
        targetType: "inline"
        script: |
           docker login slaztestacr.azurecr.io -u $(uid) -p $(pwd) 
           docker build -t slaztestacr.azurecr.io/docker-helloworld:latest  $(Build.SourcesDirectory)
           docker push slaztestacr.azurecr.io/docker-helloworld:latest
           if [ $? -ne 0 ]
             then
                echo "Docker PUSH is not successful"
                exit 1
           fi          

    - task: PublishPipelineArtifact@1
      displayName: "Publish"
      inputs:
        targetPath: '$(Build.SourcesDirectory)/deployment-playbook.yaml'
        artifact: 'dev-playbook'
        publishLocation: 'pipeline'           