- hosts: <hostname>
  tasks:
    - name: deploy  docker container
      docker_container:
        image: slaztest01acr.azurecr.io/docker-helloworld:latest
        name: docker-helloworld
        state: started
        auto_remove: true
        ports:
          - "8080:80"
